import argparse
import re

def main():
    parser = argparse.ArgumentParser(description='Generate SQL commands from ddl file to create table in sqlpp11.')
    parser.add_argument('ddl', help='path to ddl')
    parser.add_argument('target', help='path to target')
    parser.add_argument('namespace', help='namespace')
    
    args = parser.parse_args()

    with open(args.ddl, 'r') as ddl:
        contents = ddl.read(-1)
        commands = re.findall('(CREATE TABLE.*?;)', contents, re.DOTALL)

        with open(args.target, 'w') as out:
            out.write("// This file is automatically generated, do not modify.\n")
            out.write("\n#pragma once\n")
            out.write(f"namespace {args.namespace} {{\n")
            
            out.write(f"constexpr const char* const COMMANDS[] = {{\n")
            for command in commands:
                command = command.replace("\n", "\"\n\"")
                out.write(f"\"{command}\",\n")
            out.write(f"}};\n")
            out.write(f"}}\n")

if __name__ == '__main__':
    main()